version: '3.7'

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
    networks:
      - proxy


networks:
  proxy:
    driver: bridge
